#
# CQEN-QDCE Centre d'expertise appliquee en innovation
# Template openshift pour lancer des cronjobs qui font la sauvegarde de la BD
# dans un AUTRE POD OPENSHIFT
# Author: Julio Cesar Torres <julio.cesartorresmcn.gouv.qc.ca> (@cesju02)
# Date: 2022/07/04
# SPDX-License-Identifier: LiLiQ-P
# 
apiVersion: v1
kind: Template
metadata:
  name: postgres-backup-template
  annotations:
    description: 'Template for a DB container backup job'
    tags: 'database'
parameters:
  - name: DATABASE_BACKUP_KEEP
    description: 'Number of backups to keep'
    value: '7'
  - name: DATABASE_BACKUP_SCHEDULE
    description: 'Cron-like schedule expression'
    #value: '0-59/1 * * * *' # exécuter aux minutes
    value: '0 4 * * *'       # executer à 04:00 
  - name: DATABASE_USER
    description: 'database user'
    required: true
  - name: DATABASE_PASSWORD
    description: 'database user password'
    required: true
  - name: DATABASE_HOST
    description: 'Hostname of DB server'
    required: true
  - name: DATABASE_PORT
    description: 'DB Port'
    required: true
  - name: DATABASE_NAME
    description: 'Database to backup'
    required: true
  - name: DATABASE_BACKUP_VOLUME_CLAIM
    description: 'Name of the volume claim to be used as storage'
    required: true
objects:
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: cronjob-bd-backup
    spec:
      schedule: ${DATABASE_BACKUP_SCHEDULE}
      concurrencyPolicy: Forbid
      jobTemplate:
        spec:
          template:
            spec:
              volumes:
                - name: database-backup
                  persistentVolumeClaim:
                    claimName: ${DATABASE_BACKUP_VOLUME_CLAIM}
              containers:
                - name: database-backup
                  image: 'postgres:12-alpine'
                  command:
                    - 'bash'
                    - '-eo'
                    - 'pipefail'
                    - '-c'
                    - > 
                      trap "echo Backup non réussi; exit 0" ERR; 
                      FILENAME=backup-${DATABASE_NAME}-`date +%Y-%m-%d_%H%M%S`.sql.gz;
                      time (PGPASSWORD="$DATABASE_PASSWORD" /usr/local/bin/pg_dump --username=$DATABASE_USER --host=$DATABASE_HOST --port=$DATABASE_PORT --column-inserts --clean --create ${DATABASE_NAME} | gzip > /database-backup/$FILENAME); 
                      echo "";
                      echo "Backup réussi"; du -h /database-backup/$FILENAME; 
                      echo "pour restaurer le backup, faites la commande suivante dans le serveur désiré: $ psql --username=$DATABASE_USER --password --host=$DATABASE_HOST --port=$DATABASE_PORT postgres < /database-backup/<fichier> (non-compressé)"
                  env:
                    - name: DATABASE_BACKUP_KEEP
                      value: ${DATABASE_BACKUP_KEEP}
                    - name: DATABASE_USER
                      value: ${DATABASE_USER}
                    - name: DATABASE_PASSWORD
                      value: ${DATABASE_PASSWORD}
                    - name: DATABASE_HOST
                      value: ${DATABASE_HOST}
                    - name: DATABASE_PORT
                      value: ${DATABASE_PORT}
                    - name: DATABASE_NAME
                      value: ${DATABASE_NAME}
                    - name: TZ
                      value: America/New York
                  volumeMounts:
                    - name: database-backup
                      mountPath: /database-backup
              restartPolicy: Never
